const API_URL = import.meta.env.VITE_API_URL

export const sectionData = {
  barrios: {
    title: "barrio",
    titlePlural: "barrios",
    nameApi: "barrio",
    url: `${API_URL}/barrio`,
    msgs: {
      error: "Error al cargar los barrios",
      add: "Barrio agregado correctamente",
      adding: "Agregando barrio...",
      addError: "Error al agregar el barrio",
      delete: "Barrio eliminado correctamente",
      deleteError: "Error al eliminar el barrio",
      restore: "Barrio restaurado correctamente",
      restoreError: "Error al restaurar el barrio",
    },
  },
  calles: {
    title: "calle",
    titlePlural: "calles",
    nameApi: "calle",
    url: `${API_URL}/calle`,
    msgs: {
      error: "Error al cargar las calles",
      add: "Calle agregada correctamente",
      adding: "Agregando calle...",
      addError: "Error al agregar la calle",
      delete: "Calle eliminada correctamente",
      deleteError: "Error al eliminar la calle",
      restore: "Calle restaurada correctamente",
      restoreError: "Error al restaurar la calle",
    },
  },
  usuarios: {
    title: "usuario",
    titlePlural: "usuarios",
    nameApi: "nombre",
    url: `${API_URL}/usuario`,
    msgs: {
      error: "Error al cargar los usuarios",
      add: "Usuario agregado correctamente",
      adding: "Agregando usuario...",
      addError: "Error al agregar el usuario",
      delete: "Usuario eliminado correctamente",
      deleteError: "Error al eliminar el usuario",
      restore: "Usuario restaurado correctamente",
      restoreError: "Error al restaurar el usuario",
    },
  },
  areas: {
    title: "área",
    titlePlural: "áreas",
    nameApi: "area",
    url: `${API_URL}/area`,
    msgs: {
      error: "Error al cargar las áreas",
      add: "Área agregada correctamente",
      adding: "Agregando área...",
      addError: "Error al agregar el área",
      delete: "Área eliminada correctamente",
      deleteError: "Error al eliminar el área",
      restore: "Área restaurada correctamente",
      restoreError: "Error al restaurar el área",
    },
  },
  "tipos-de-reclamos": {
    title: "tipo de reclamo",
    titlePlural: "tipos de reclamos",
    nameApi: "tipo",
    url: `${API_URL}/tipo-reclamo`,
    msgs: {
      error: "Error al cargar los tipos de reclamos",
      add: "Tipo de reclamo agregado correctamente",
      adding: "Agregando tipo de reclamo...",
      addError: "Error al agregar el tipo de reclamo",
      delete: "Tipo de reclamo eliminado correctamente",
      deleteError: "Error al eliminar el tipo de reclamo",
      restore: "Tipo de reclamo restaurado correctamente",
      restoreError: "Error al restaurar el tipo de reclamo",
    },
  },
}
